/**
 * Webhook Payload Types
 * 
 * TypeScript interfaces for webhook communication between Next.js and n8n.
 * These types match the webhook contract defined in docs/ARCHITECTURE.md
 */

// ============================================================================
// Outbound Webhook Payload (Next.js → n8n)
// ============================================================================

export interface OutboundWebhookPayload {
  version: "v1";
  runId: string; // UUID generated by Next.js
  userId: string; // Supabase user ID
  timestamp: string; // ISO 8601
  config: {
    industry: string; // Selected industry identifier (slug)
    rssSources: Array<{
      id: string; // RSS source ID from database
      url: string; // RSS feed URL
      name: string; // User-friendly name
    }>;
    promptInstructions: string; // User-provided prompt customization
    outputFormats: Array<"blog" | "social" | "email" | "webhook">;
    destination: {
      type: "webhook" | "social" | "email" | "none";
      config?: {
        webhookUrl?: string;
        socialPlatforms?: string[];
        emailRecipients?: string[];
      };
    };
    schedule?: {
      cronExpression: string; // For future scheduled runs
    };
  };
}

// ============================================================================
// Inbound Webhook Payload (n8n → Next.js)
// ============================================================================

export interface InboundWebhookPayload {
  version: "v1";
  runId: string; // Echoed from outbound payload
  status: "success" | "partial" | "error" | "progress"; // Added "progress" for streaming updates
  timestamp: string; // ISO 8601
  // For progress updates (status === "progress")
  progress?: {
    message: string; // e.g., "Fetching News Sources", "robopost agent engaged"
    status?: "info" | "success" | "warning" | "error";
  };
  // For final updates (status === "success" | "partial" | "error")
  results?: Array<{
    outputType: "blog" | "social" | "email" | "webhook";
    content: string; // Generated content
    metadata: {
      sources: Array<{
        url: string;
        title: string;
        publishedAt: string;
      }>;
      model?: string; // n8n internal (optional)
      tokensUsed?: number; // n8n internal (optional)
    };
  }>;
  error?: {
    code: string;
    message: string;
    details?: unknown;
  };
}

// ============================================================================
// API Request/Response Types
// ============================================================================

/**
 * Request body for triggering a new agent run
 */
export interface RunTriggerRequest {
  sourceIds: string[]; // Array of user_sources.id
  industryId?: string; // Optional industry UUID
  promptInstructions?: string; // Optional custom prompt
  outputFormats: Array<"blog" | "social" | "email" | "webhook">;
  destination: {
    type: "webhook" | "social" | "email" | "none";
    config?: {
      webhookUrl?: string;
      socialPlatforms?: string[];
      emailRecipients?: string[];
    };
  };
}

/**
 * Response from run trigger API
 */
export interface RunTriggerResponse {
  runId: string;
  status: "pending";
  message: string;
}

